version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Running pre-build commands"

  build:
    commands:
      - echo "Building the application"
      - python main.py

  post_build:
    commands:
      - echo "Running post-build commands"

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/root/.cache/pip'
